### ISSUE TITLE
Question on the origin service recognition

### ISSUE THREAD

**Issue by thundron** [Agile-IoT/enforcer-yaml-spec#4]
Is it correct to say that we need to manage permissions through the Authorization header and ignore the origin service the HTTP call comes from?

**Comment by nopbyte** [comment]
What exactly do you mean by "ignore" the origin service the HTTP call comes from?

The idea is to check the Authorization header. CORS makes the browser check when there are requests to the enforcer from a separate domain. 
So, in a sense there are headers affecting the access to the enforcer, but this happens in the browser.

The solution to this is to have the enforcer to support the Options CORS headers to allow external Origins to use the enforcer.

**Comment by nopbyte** [comment]
@thundron if that was clear, feel free to close the issue.

**Comment by thundron** [comment]
@nopbyte I mean that the Authorization header refers to a user rather than a service, the latter being what I thought we needed to validate access from

**Comment by nopbyte** [comment]
Ohhh ok. Yes, we only need the Authorization header.  These evaluations are based around the user, not the services. I am closing this issue now. If needed, you can reopen this issue.
